[package]
name = "bluetooth_timeout"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.61.1", features = ["Win32", "Win32_Devices", "Win32_Devices_Bluetooth"] }
anyhow = "1.0.97"
tracing-subscriber = "0.3.19"
tracing = "0.1.41"