[package]
name = "windows_bluetooth"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
windows = { version = "0.61.1", features = ["Win32", "Win32_Devices", "Win32_Devices_Bluetooth"] }
